version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:admin@db:5432/postgres?schema=task_app_dfm
      IS_DOCKER: true
    ports:
      - '3000:3000'
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"